spring.application.name=softlearning
server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/softlearningizanweb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# El dialecto se detecta automaticamente

# JWT Configuration
jwt.secret.key=c29mdGxlYXJuaW5nLXNlY3JldC1rZXktMjAyNC1tdXN0LWJlLWF0LWxlYXN0LTI1Ni1iaXRzLWxvbmctZm9yLXNlY3VyaXR5
jwt.time.expiration=3600000
jwt.refresh-token.expiration=86400000
